[project]
name = "Plutus"
version = "0.1.0"
authors = [{ name = "Plutus Contributors" }]
description = "A simple application for tracking precious metal stacks."
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    # Per https://www.pythonguis.com/pyqt6/, the license is not overly important
    # and PySide6 and PyQt6 are very similar so I picked the older one that has
    # the possibility of support.
    "PyQt6 >= 6.5",
    # These are needed for getting the current gold, silver and other spot prices
    "requests >= 2.30",
    # Provides SQLCipher-backed SQLite encryption wheels for Linux, Windows, and macOS.
    "sqlcipher3-wheels >= 0.5.7",
]

[project.optional-dependencies]
build = [
    "pyinstaller >= 6.19",
]
docs = [
    "sphinx >= 9.0",
    "furo >= 2025.12.19",
    "ghp-import >= 2.1",
]

[project.scripts]
plutus = "plutus.app:main"

[tool.flit.module]
name = "plutus"
